### ISSUE TITLE
リンク切れしてる

### ISSUE THREAD

**Issue by ghost** [Comamoca/Comamoca#1]
redditとqiitaのユーザー名が多分あってない...？
あと，qiitaの後のimgが表示されてない↓
![image](https://user-images.githubusercontent.com/89781396/139553893-f5ad5288-92dc-4249-89d9-8f5e70e12bfc.png)

**Comment by Comamoca** [comment]
issueありがとう。
ステータスを表示するコードをコードを、Twitterユーザー名で置換したから存在しないユーザー名を指定してしまっているらしい。
Twitterユーザー名に対応したIDの各アカウントを作っているから、しばらくすれば表示されると思う。

**Comment by Comamoca** [comment]
アカウントの作成が完了して、表示が正常なのも確認できたからissue閉じます。
